import {Login, SignUp, InputOTP} from './Auth';
import {
    
    HomeScreen,
    MessageScreen,
    ServiceScreen,
    AccountScreen,
    AppointmentSchedule,
    Bills,
    Contracts,
    LikedPost,
    ManaPost,
    ManaServiceOrder,
    ReportProblem,
    TermPolicies,
    DesignRoomService,
    GasService,
    LaundryService,
    Notification,
    RepairService,
    ShoppingCart,
    TransportService,
    WaterService,
    SearchPosting,
    SearchForNews,
    DetailRoom,
    ImageRoomDetail,
    LandlordInformationDetail,
    ProductDetails,
    ImageProductDetails,
    MessageDetail,
    RoomSearchPost,
    RoommateSearchPost,
    OrderConfirmationDetail,
    ShoppingCartDetail,
    UpdateInformation,
    FindRoomAroundHere,

} from './Main';

const Screens = {
    Login,
    SignUp,
    InputOTP,
    HomeScreen,
    MessageScreen,
    ServiceScreen,
    AccountScreen,
    AppointmentSchedule,
    Bills,
    Contracts,
    LikedPost,
    ManaPost,
    ManaServiceOrder,
    ReportProblem,
    TermPolicies,
    DesignRoomService,
    GasService,
    LaundryService,
    Notification,
    RepairService,
    ShoppingCart,
    TransportService,
    WaterService,
    SearchPosting,
    SearchForNews,
    DetailRoom,
    ImageRoomDetail,
    LandlordInformationDetail,
    ProductDetails,
    ImageProductDetails,
    MessageDetail,
    RoomSearchPost,
    RoommateSearchPost,
    OrderConfirmationDetail,
    ShoppingCartDetail,
    UpdateInformation,
    FindRoomAroundHere,

};
export {Screens} 