export enum ROUTE_TAB {
    TAB = 'TAB',
    HOME_TAB = 'HOME_TAB',
    SERVICE_TAB = 'SERVICE_TAB',
    MESSAGE_TAB = 'MESSAGE_TAB',
    ACCOUNT_TAB = 'ACCOUNT_TAB',
}

export enum ROUTE_MAIN {
    ROUTE_MAIN = 'ROUTE_MAIN',
    APPOINTMENT_SCHEDULE = 'APPOINTMENT_SCHEDULE',
    BILLS = 'BILLS',
    CONTRACT = 'CONTRACT',
    DESIGN_ROOM_SERVICE = 'DESIGN_ROOM_SERVICE',
    GAS_SERVICE = 'GAS_SERVICE',
    LAUNDRY_SERVICE = 'LAUNDRY_SERVICE',
    LIKE_POST = 'LIKE_POST',
    MANAGE_POST = 'MANAGE_POST',
    MANA_SERVICE_ORDER = 'MANA_SERVICE_ORDER',
    NOTIFICATION = 'NOTIFICATION',
    REPAIR_SERVICE = 'REPAIR_SERVICE',
    REPORT_PROBLEM = 'REPORT_PROBLEM',
    SEARCH_POSTING = 'SEARCH_POSTING',
    SHOPPING_CART = 'SHOPPING_CART',
    TERM_POLICIES = 'TERM_POLICIES',
    TRANSPORT_SERVICE = 'TRANSPORT_SERVICE',
    WATER_SERVICE = 'WATER_SERVICE',

}