
import {
    HomeScreen,
    MessageScreen,
    ServiceScreen,
    AccountScreen,
    AppointmentSchedule,
    Bills,
    Contracts,
    LikedPost,
    ManaPost,
    ManaServiceOrder,
    ReportProblem,
    TermPolicies,
    DesignRoomService,
    GasService,
    LaundryService,
    Notification,
    RepairService,
    ShoppingCart,
    TransportService,
    WaterService,
    SearchPosting,
    SearchForNews,

} from './Main';

const Screens = {
    HomeScreen,
    MessageScreen,
    ServiceScreen,
    AccountScreen,
    AppointmentSchedule,
    Bills,
    Contracts,
    LikedPost,
    ManaPost,
    ManaServiceOrder,
    ReportProblem,
    TermPolicies,
    DesignRoomService,
    GasService,
    LaundryService,
    Notification,
    RepairService,
    ShoppingCart,
    TransportService,
    WaterService,
    SearchPosting,
    SearchForNews,
};
export {Screens} 